# Generated by Django 4.2.5 on 2023-12-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_level_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
