# Generated by Django 4.2.5 on 2023-12-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_course_level_delete_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_profile', models.ImageField(upload_to='Media/author')),
                ('name', models.CharField(max_length=100, null=True)),
                ('about_author', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='author2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.author2'),
        ),
    ]
