# Generated by Django 4.2.5 on 2024-01-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='job_role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
