# Generated by Django 4.2.5 on 2024-01-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_course_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
